### ISSUE TITLE
Filter for nearnormalHemisphericalSolarTransmittance fails

### ISSUE THREAD

**Issue by christoph-maurer** [building-envelope-data/metabase#138]
When I use the the [metabase frontend](https://www.buildingenvelopedata.org/data/optical) after the last deploy without any filter, I receive only data sets from the TestLab Solar Facades Database. 

When I try to find components with nearnormalHemisphericalSolarTransmittance greaterThanOrEqualTo 0 , I don't get any results.

Therefore, I tried the graphql endpoint of IGSDB. With
```
query {
  byComponentId: allOpticalData(
    where: {
      nearnormalHemisphericalSolarTransmittances: {
        some: { greaterThanOrEqualTo: 0 }
      }
    }
  ) {
    nodes {
      uuid
      resourceTree {
        root {
          value {
            locator
          }
        }
      }
    }
  } 
}
```
I receive
```
{
  "data": {
    "byComponentId": {
      "nodes": [
        {
          "uuid": "a89bdb38-c90d-4ec2-9af0-580609391e17",
          "resourceTree": {
            "root": {
              "value": {
                "locator": "https://igsdb-icon.herokuapp.com/api/v1/products/185/?json_format=buildingenvelopedata.org"
              }
            }
          }
        },
        {
          "uuid": "8f74605b-b5d9-43c5-b174-7d551d086bb7",
          "resourceTree": {
            "root": {
              "value": {
                "locator": "https://igsdb-icon.herokuapp.com/api/v1/products/186/?json_format=buildingenvelopedata.org"
              }
            }
          }
        }, [...]
``` 
which looks fine.

Next, I tried to query the [metabase backend](https://www.buildingenvelopedata.org/graphql/) with
```
query {
  MBforResourcesWithDataFormat: databases {
    nodes {
      uuid
      name
      locator
      allOpticalData(
        where: {
          nearnormalHemisphericalSolarTransmittances: { some: { greaterThanOrEqualTo: 0 }
      }
      ) {
        nodes {
          resourceTree {
            root {
              value {
                locator
              }
            }
          }
        }
      }
    }
  }
}
```
but I don't get a response. Do you know how this could be solved?

**Comment by simon-wacker** [comment]
There is at least one optical data result from the IGSDB whose field `id` has the value `null` although `id` is non-nullable. This is a fundamental type error resulting in an empty result set from the IGSDB. When you queried the IGSDB directly you did not ask for `id` (you only asked for `uuid`) and this is why the error did not occur then.

**Comment by simon-wacker** [comment]
If we knew the UUID of the erroneous data set we could exclude it explicitly. I don't know it though. I reopened issue https://github.com/building-envelope-data/api/issues/275#issuecomment-1039230502 If Stephen cannot fix it in time, I'll remove the possibility to query for `id`, `warnings`, and the other non-nullable fields.

**Comment by christoph-maurer** [comment]
Danke, lieber Simon!Mit freundlichen Grüßen / Best regards,
Christoph Maurer
--
Dr.-Ing. Christoph Maurer
Project Manager
Solar Building Envelopes
Energy Efficient Buildings
Fraunhofer Institute for Solar Energy Systems ISE
Heidenhofstr. 2, 79110 Freiburg, Germany
Phone: +49 761 4588-5667
***@***.***
***@***.*** (invoice processing)
Web: www.ise.fraunhofer.de
Blog: blog.innovation4e.de
Social Media: Facebook | Twitter | LinkedIn | YouTube

If you would like to remain informed and up-to-date on the latest news,
subscribe to our newsletter and receive all the relevant information about our latest research activities. -> Register here-----"Simon Wacker" ***@***.***> wrote: -----To: "building-envelope-data/metabase" ***@***.***>From: "Simon Wacker" ***@***.***>Date: 14/02/2022 17:20Cc: "Christoph Maurer" ***@***.***>, "Author" ***@***.***>Subject: Re: [building-envelope-data/metabase] Filter for nearnormalHemisphericalSolarTransmittance fails (Issue #138)
If we knew the UUID of the erroneous data set we could exclude it explicitly. I don't know it though. I reopened issue building-envelope-data/api#275 (comment) If Stephen cannot fix it in time, I'll remove the possibility to query for id, warnings, and the other non-nullable fields.

**Comment by christoph-maurer** [comment]
@simon-wacker Thanks a lot for identifying the issue so quickly! Stephen already fixed it.
