### ISSUE TITLE
Scale the image compared to the text

### ISSUE THREAD

**Issue by christoph-maurer** [building-envelope-data/metabase#145]
On https://www.buildingenvelopedata.org/, the image of the network of product databases is much larger than the text.

![image](https://user-images.githubusercontent.com/33456252/217549108-fc0a13eb-252e-45a7-a28d-00ca545be4b5.png)

It would be good if the image had the same width as the text. An nice alternative could be that the space between the fields "Home" and "Register" is separated into to columns with equal width, one for the text and one for the image.

**Comment by simon-wacker** [comment]
Fixed in https://github.com/building-envelope-data/metabase/commit/fccbb32274e8e6c09611e607771e4bdf6cc06512
