### ISSUE TITLE
Update the link to IGSDB from version 1 to version 2

### ISSUE THREAD

**Issue by christoph-maurer** [building-envelope-data/metabase#180]
Please exchange the URL of the database IGSDB `https://igsdb-icon.herokuapp.com/icon_graphql/` by `https://igsdb-v2.herokuapp.com/graphql/` and deploy `metabase`.

Please verify that the entries of IGSDB can be found now with a query for `allData` (see https://github.com/building-envelope-data/api/issues/301).

**Comment by simon-wacker** [comment]
I switched from version 1 to version 2. See https://www.buildingenvelopedata.org/databases/48994b60-670d-488d-aaf7-53333a64f1d6
