### ISSUE TITLE
operating state and `deleteInstitution`

### ISSUE THREAD

**Issue by christoph-maurer** [building-envelope-data/metabase#184]
@shreyaponnamma has asked: "Should any changes be made to the delete button which is already there in the front end?"

 @christoph-maurer answers: "I don't see a delete button in the front end. I see `deleteInstitution` in [type-defs.graphqls](https://github.com/building-envelope-data/metabase/blob/46c522f4c668521f75baa2036dea59e031e8e4a5/frontend/type-defs.graphqls#L952). But I'm not sure if we should exchange it by `makeInstitutionNotOperating`." 

@simon-wacker What do you recommend?

**Comment by simon-wacker** [comment]
@shreyaponnamma04 The delete button should stay there. Marking an institution as not operating is similar but different. The deleting institutions only works when they are not associated to any components, data formats and so forth. It can be used for example when someone creates an institution and then reconsiders it shortly after before associating anything with the institution or when there are bogus/spam institutions around created by a bot. Marking an institution as not operating though should also work when there are components, data formats and so forth associated to the institution. Not operating institutions can still be found in searches as they are still relevant in some sense, whereas deleted institutions are truly gone.

**Comment by shreyaponnamma** [comment]
Solved by #183
