### ISSUE TITLE
Legal notice and data protection information missing

### ISSUE THREAD

**Issue by christoph-maurer** [building-envelope-data/metabase#197]
Hi,

when I click on "Legal Notice" or "Data Protection Information" on https://www.buildingenvelopedata.org/ , I don't see them. Please make them visible.

![image](https://github.com/user-attachments/assets/cadb92a4-2de4-479c-ac07-289522b914c5)

**Comment by simon-wacker** [comment]
I just checked and it works locally as well as in production. I fetch the information from ISE web servers (that's what ISE wanted back then). It may have been the case that for some reason those web servers were unreachable.
