### ISSUE TITLE
Remove duplicate of a method

### ISSUE THREAD

**Issue by christoph-maurer** [building-envelope-data/metabase#202]
Unfortunately, I have created the method `Lambda900 measurement` twice, with the uuids `b00c1e42-2b8d-44a6-8741-680f5e935518`  and `98483d53-0236-486a-95bc-b1ba056c288c`. How can I delete the duplicate with the uuid `98483d53-0236-486a-95bc-b1ba056c288c`?

**Comment by simon-wacker** [comment]
Well, you can't. Deleting methods is problematic in general as they may already be used/referenced and we can't really know if that is the case. A good user interface would probably have an undo button that works just after creation or have a delete button that works for 5 minutes after creation. I'll delete the method via `psql`.
