### ISSUE TITLE
Implement `definitionOfSurfacesAndPrimeDirection` in GraphQL

### ISSUE THREAD

**Issue by christoph-maurer** [building-envelope-data/metabase#204]
@simon-wacker Can you please implement https://github.com/building-envelope-data/api/blob/ce84a83c2b3a481ea95208a7fc2191655911c68e/schemas/component.json#L263 in GraphQL?

**Comment by simon-wacker** [comment]
@christoph-maurer Is there a reason that the name is prefixed with `definitionOf`? Why not just name it `surfacesAndPrimeDirections`?

**Comment by christoph-maurer** [comment]
```
`prime`:{
  `surface`
  `direction`
},
`switchableLayers`
```
