### ISSUE TITLE
Send emails through some paid service

### ISSUE THREAD

**Issue by simon-wacker** [building-envelope-data/metabase#6]
For an overview of services see [7 Best Transactional Email Services: Sendgrid vs. Mandrill & More](https://www.ventureharbour.com/transactional-email-service-best-mandrill-vs-sendgrid-vs-mailjet/). I have personal experience with [SendGrid](https://sendgrid.com/) (by Twilio). Other options are [SendInBlue](https://de.sendinblue.com/) and [MailGun](https://www.mailgun.com/).

@christoph-maurer Could you ask for permission for us to use such a service? Preferably SendGrid? Or does the institution offer a similar service to send emails that we need to use (I would still prefer SendGrid though)?

**Comment by christoph-maurer** [comment]
I have opened a ticket and answer as soon as I get more information.

**Comment by simon-wacker** [comment]
Some notes on the current state of affairs: The institute does not want us to use a paid service. They try to make it possible for us to use their mail transfer agent. If that should not work, then we may consider using [postal](https://github.com/postalhq/postal) (see [also](https://postal.atech.media/)). There is a [third-party Dockerfile](https://github.com/tiredofit/docker-postal) to take inspiration from. For a comparison of good-old mail transfer agents see [Postfix vs. Sendmail vs. Exim](https://blog.mailtrap.io/postfix-sendmail-exim/).
